// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: protos/receiver.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EdgeReceiverClient is the client API for EdgeReceiver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EdgeReceiverClient interface {
	Send(ctx context.Context, in *ChatMessage, opts ...grpc.CallOption) (*Empty, error)
}

type edgeReceiverClient struct {
	cc grpc.ClientConnInterface
}

func NewEdgeReceiverClient(cc grpc.ClientConnInterface) EdgeReceiverClient {
	return &edgeReceiverClient{cc}
}

func (c *edgeReceiverClient) Send(ctx context.Context, in *ChatMessage, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/EdgeReceiver/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EdgeReceiverServer is the server API for EdgeReceiver service.
// All implementations must embed UnimplementedEdgeReceiverServer
// for forward compatibility
type EdgeReceiverServer interface {
	Send(context.Context, *ChatMessage) (*Empty, error)
	mustEmbedUnimplementedEdgeReceiverServer()
}

// UnimplementedEdgeReceiverServer must be embedded to have forward compatible implementations.
type UnimplementedEdgeReceiverServer struct {
}

func (UnimplementedEdgeReceiverServer) Send(context.Context, *ChatMessage) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedEdgeReceiverServer) mustEmbedUnimplementedEdgeReceiverServer() {}

// UnsafeEdgeReceiverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EdgeReceiverServer will
// result in compilation errors.
type UnsafeEdgeReceiverServer interface {
	mustEmbedUnimplementedEdgeReceiverServer()
}

func RegisterEdgeReceiverServer(s grpc.ServiceRegistrar, srv EdgeReceiverServer) {
	s.RegisterService(&EdgeReceiver_ServiceDesc, srv)
}

func _EdgeReceiver_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeReceiverServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EdgeReceiver/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeReceiverServer).Send(ctx, req.(*ChatMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// EdgeReceiver_ServiceDesc is the grpc.ServiceDesc for EdgeReceiver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EdgeReceiver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "EdgeReceiver",
	HandlerType: (*EdgeReceiverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _EdgeReceiver_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/receiver.proto",
}
